#!/usr/bin/env sh

# General icons
export ICON_APPLE=प्पल
export ICON_SPACE=󰎤
export ICON_APPS=apps
export ICON_MENU=󰃖
export ICON_PACKAGE=󰏖
export ICON_COG= settings
export ICON_RELOAD=󰑓
export ICON_LOCK= padlock
export ICON_POWER=󰐥
export ICON_BELL= notification
export ICON_BELL_DOT= notification with dot
export ICON_KEYBOARD= keyboard
export ICON_MOUSE= mouse
export ICON_CPU=PU
export ICON_RAM=󰇖
export ICON_DISK=󰋊
export ICON_NETWORK=󰛵
export ICON_WIFI=󰖩
export ICON_WIFI_OFF=󰖪
export ICON_BLUETOOTH=󰂯
export ICON_BATTERY=󰁺
export ICON_BATTERY_CHARGING=󰢟
export ICON_BATTERY_FULL=󰁹
export ICON_BATTERY_LOW=󰁻
export ICON_VOLUME_HIGH=󰕾
export ICON_VOLUME_LOW=󰖀
export ICON_VOLUME_MUTED=󰕿
export ICON_BRIGHTNESS_HIGH= brightness high
export ICON_BRIGHTNESS_LOW= brightness low
export ICON_BRIGHTNESS_OFF= brightness off
export ICON_MICROPHONE= microphone
export ICON_MICROPHONE_OFF= microphone off
export ICON_PLAY= play
export ICON_PAUSE= pause
export ICON_PREV= backward
export ICON_NEXT= forward
export ICON_MUSIC=󰎄
export ICON_SPOTIFY=󰓇
export ICON_CHROME=rome
export ICON_SAFARI=󰖔
export ICON_FIREFOX= browser
export ICON_VSCODE=󰨞
export ICON_TERMINAL=󰆍
export ICON_FINDER= folder
export ICON_MAIL= email
export ICON_CALENDAR=󰃰
export ICON_MESSAGES= messaging
export ICON_DISCORD=󰓓
export ICON_SLACK=󰒱
export ICON_TEAMS= teams
export ICON_ZOOM=󰖠
export ICON_PHOTOS=󰄄
export ICON_PHOTOSHOP=󰎆
export ICON_ILLUSTRATOR=󰎅
export ICON_FIGMA=EF
export ICON_SKETCH= sketch
export ICON_XCODE= code
export ICON_GIT=󰊢
export ICON_GITHUB=󰊣
export ICON_GITLAB=󰊤
export ICON_DOCKER=󰡨
export ICON_KUBERNETES=󰠹
export ICON_AWS=AWS
export ICON_AZURE=󰠴
export ICON_GCP=GCP
export ICON_LINUX=󰌽
export ICON_WINDOWS= windows
export ICON_APPLE_OS=OS
export ICON_ANDROID= android
export ICON_IOS= iOS
export ICON_HOMEBREW= homebrew
export ICON_NPM= node
export ICON_YARN= yarn
export ICON_PYTHON= python
export ICON_JAVASCRIPT=avascript
export ICON_TYPESCRIPT= typescript
export ICON_REACT= react
export ICON_ANGULAR= angular
export ICON_VUE= vue
export ICON_SWIFT= swift
export ICON_KOTLIN= kotlin
export ICON_JAVA= java
export ICON_GO= go
export ICON_RUST= rust
export ICON_PHP= php
export ICON_RUBY= ruby
export ICON_PERL= perl
export ICON_SHELL= shell
export ICON_DART= dart
export ICON_FLUTTER= flutter
export ICON_C= programming
export ICON_CPP= programming
export ICON_CSHARP= programming
export ICON_FSHARP= programming
export ICON_POWERSHELL= powershell
export ICON_SQL= database
export ICON_MONGODB= database
export ICON_REDIS= database
export ICON_POSTGRESQL= database
export ICON_MYSQL= database
export ICON_MARIADB= database
export ICON_ORACLE= database
export ICON_SQLSERVER= database
export ICON_ELASTICSEARCH= database
export ICON_KAFKA= database
export ICON_RABBITMQ= database
export ICON_REDHAT= linux
export ICON_UBUNTU= linux
export ICON_DEBIAN= linux
export ICON_FEDORA= linux
export ICON_ARCH= linux
export ICON_CENTOS= linux
export ICON_SUSE= linux
export ICON_GENTOO= linux
export ICON_FREEBSD= freebsd
export ICON_OPENBSD= openbsd
export ICON_NETBSD= netbsd
export ICON_MACOS= macos
export ICON_WINDOWS_OS= windows
export ICON_LINUX_OS= linux
export ICON_ANDROID_OS= android
export ICON_IOS_OS= iOS
export ICON_WEB= globe
export ICON_CLOUD= cloud
export ICON_SERVER= server
export ICON_DATABASE= database
export ICON_TERMINAL_ALT= terminal
export ICON_FILE= document
export ICON_FOLDER= folder
export ICON_TRASH= trash
export ICON_INFO= info
export ICON_WARNING= warning
export ICON_ERROR= error
export ICON_CHECK= check
export ICON_CROSS= cross
export ICON_PLUS= plus
export ICON_MINUS= minus
export ICON_UP= up
export ICON_DOWN= down
export ICON_LEFT= left
export ICON_RIGHT= right
export ICON_ARROW_UP= arrow up
export ICON_ARROW_DOWN= arrow down
export ICON_ARROW_LEFT= arrow left
export ICON_ARROW_RIGHT= arrow right
export ICON_EXTERNAL_LINK= external link
export ICON_LINK= link
export ICON_UNLINK= unlink
export ICON_SEARCH= search
export ICON_STAR= star
export ICON_HEART= heart
export ICON_THUMBS_UP= thumbs up
export ICON_THUMBS_DOWN= thumbs down
export ICON_HOME= home
export ICON_USER= user
export ICON_USERS= users
export ICON_GROUP= group
export ICON_SETTINGS= settings
export ICON_GEAR= gear
export ICON_TOOLS= tools
export ICON_BRUSH= brush
export ICON_PAINT= paint
export ICON_PALETTE= palette
export ICON_CAMERA= camera
export ICON_VIDEO= video
export ICON_IMAGE= image
export ICON_MICROPHONE_ALT= microphone
export ICON_HEADPHONES= headphones
export ICON_SPEAKER= speaker
export ICON_MONITOR= monitor
export ICON_LAPTOP= laptop
export ICON_TABLET= tablet
export ICON_PHONE= phone
export ICON_WATCH= watch
export ICON_PRINTER= printer
export ICON_SCANNER= scanner
export ICON_FAX= fax
export ICON_USB= usb
export ICON_ETHERNET= ethernet
export ICON_GLOBE= globe
export ICON_LOCATION= location
export ICON_MAP= map
export ICON_COMPASS= compass
export ICON_CALENDAR_ALT= calendar
export ICON_CLOCK= clock
export ICON_TIMER= timer
export ICON_STOPWATCH= stopwatch
export ICON_ALARM= alarm
export ICON_HISTORY= history
export ICON_BOOKMARK= bookmark
export ICON_BOOK= book
export ICON_LIBRARY= library
export ICON_READ= read
export ICON_EDIT= edit
export ICON_COPY= copy
export ICON_PASTE= paste
export ICON_CUT= cut
export ICON_DELETE= delete
export ICON_SAVE= save
export ICON_UPLOAD= upload
export ICON_DOWNLOAD= download
export ICON_SHARE= share
export ICON_PRINT= print
export ICON_NEW= new
export ICON_OPEN= open
export ICON_CLOSE= close
export ICON_EXIT= exit
export ICON_FULLSCREEN= fullscreen
export ICON_MINIMIZE= minimize
export ICON_MAXIMIZE= maximize
export ICON_RESTORE= restore
export ICON_REFRESH= refresh
export ICON_SYNC= sync
export ICON_UNDO= undo
export ICON_REDO= redo
export ICON_ZOOM_IN= zoom in
export ICON_ZOOM_OUT= zoom out
export ICON_QUESTION= question
export ICON_EXCLAMATION= exclamation
export ICON_ASTERISK= asterisk
export ICON_HASH= hash
export ICON_AT= at
export ICON_PERCENT= percent
export ICON_DOLLAR= dollar
export ICON_EURO= euro
export ICON_POUND= pound
export ICON_YEN= yen
export ICON_RUPEE= rupee
export ICON_WON= won
export ICON_BITCOIN= bitcoin
export ICON_ETHEREUM= ethereum
export ICON_LITECOIN= litecoin
export ICON_DOGECOIN= dogecoin
export ICON_XRP= xrp
export ICON_MONERO= monero
export ICON_ZEC= zec
export ICON_DASH= dash
export ICON_TRON= tron
export ICON_CARDANO= cardano
export ICON_POLKADOT= polkadot
export ICON_SOLANA= solana
export ICON_AVAX= avax
export ICON_BINANCE= binance
export ICON_COINBASE= coinbase
export ICON_GEMINI= gemini
export ICON_KRAKEN= kraken
export ICON_KUCOIN= kucoin
export ICON_BYBIT= bybit
export ICON_FTX= ftx
export ICON_OKX= okx
export ICON_HUOBI= huobi
export ICON_GATEIO= gateio
export ICON_BITFINEX= bitfinex
export ICON_BITSTAMP= bitstamp
export ICON_CRYPTOCOM= cryptocom
export ICON_BLOCKFI= blockfi
export ICON_CELSIUS= celsius
export ICON_NEXO= nexo
export ICON_LEDGER= ledger
export ICON_TREZOR= trezor
export ICON_METAMASK= metamask
export ICON_TRUSTWALLET= trustwallet
export ICON_COINOMI= coinomi
export ICON_EXODUS= exodus
export ICON_ATOMIC= atomic
export ICON_ELECTRUM= electrum
export ICON_MYCELIUM= mycelium
export ICON_GREENWALLET= greenwallet
export ICON_BLUEWALLET= bluewallet
export ICON_SAMOURAI= samourai
export ICON_WASABI= wasabi
export ICON_COLDCARD= coldcard
export ICON_PASSPORT= passport
export ICON_KEYSTONE= keystone
export ICON_ELLIPAL= ellipal
export ICON_SAFEPAL= safepal
export ICON_BALLET= ballet
export ICON_TANGEM= tangem
export ICON_ARZ= arz
export ICON_BITBOX= bitbox
export ICON_KEEPKEY= keepkey
export ICON_COBO= cobo
export ICON_IMTOKEN= imtoken
export ICON_ALPHA= alpha
export ICON_BETA= beta
export ICON_GAMMA= gamma
export ICON_DELTA= delta
export ICON_EPSILON= epsilon
export ICON_ZETA= zeta
export ICON_ETA= eta
export ICON_THETA= theta
export ICON_IOTA= iota
export ICON_KAPPA= kappa
export ICON_LAMBDA= lambda
export ICON_MU= mu
export ICON_NU= nu
export ICON_XI= xi
export ICON_OMICRON= omicron
export ICON_PI= pi
export ICON_RHO= rho
export ICON_SIGMA= sigma
export ICON_TAU= tau
export ICON_UPSILON= upsilon
export ICON_PHI= phi
export ICON_CHI= chi
export ICON_PSI= psi
export ICON_OMEGA= omega
export ICON_INFINITY= infinity
export ICON_PERCENTAGE= percentage
export ICON_PLUS_MINUS= plus minus
export ICON_MULTIPLY= multiply
export ICON_DIVIDE= divide
export ICON_EQUAL= equal
export ICON_NOT_EQUAL= not equal
export ICON_LESS_THAN= less than
export ICON_GREATER_THAN= greater than
export ICON_LESS_THAN_EQUAL= less than equal
export ICON_GREATER_THAN_EQUAL= greater than equal
export ICON_APPROXIMATELY= approximately
export ICON_CONGRUENT= congruent
export ICON_SIMILAR= similar
export ICON_PROPORTIONAL= proportional
export ICON_THEREFORE= therefore
export ICON_BECAUSE= because
export ICON_FOR_ALL= for all
export ICON_EXISTS= exists
export ICON_NOT_EXISTS= not exists
export ICON_EMPTY_SET= empty set
export ICON_ELEMENT_OF= element of
export ICON_NOT_ELEMENT_OF= not element of
export ICON_SUBSET= subset
export ICON_SUPERSET= superset
export ICON_NOT_SUBSET= not subset
export ICON_NOT_SUPERSET= not superset
export ICON_UNION= union
export ICON_INTERSECTION= intersection
export ICON_INTEGRAL= integral
export ICON_SUMMATION= summation
export ICON_PRODUCT= product
export ICON_SQUARE_ROOT= square root
export ICON_CUBE_ROOT= cube root
export ICON_FOURTH_ROOT= fourth root
export ICON_NTH_ROOT= nth root
export ICON_PARTIAL_DIFFERENTIAL= partial differential
export ICON_NABLA= nabla
export ICON_GRADIENT= gradient
export ICON_DIVERGENCE= divergence
export ICON_CURL= curl
export ICON_LAPLACIAN= laplacian
export ICON_DEL= del
export ICON_DOT_PRODUCT= dot product
export ICON_CROSS_PRODUCT= cross product
export ICON_TENSOR_PRODUCT= tensor product
export ICON_OUTER_PRODUCT= outer product
export ICON_INNER_PRODUCT= inner product
export ICON_DIRECT_SUM= direct sum
export ICON_DIRECT_PRODUCT= direct product
export ICON_TENSOR_SUM= tensor sum
export ICON_TENSOR_DIFFERENCE= tensor difference
export ICON_TENSOR_DIVISION= tensor division
export ICON_TENSOR_POWER= tensor power
export ICON_TENSOR_SQUARE_ROOT= tensor square root
export ICON_TENSOR_CUBE_ROOT= tensor cube root
export ICON_TENSOR_NTH_ROOT= tensor nth root
export ICON_TENSOR_INTEGRAL= tensor integral
export ICON_TENSOR_SUMMATION= tensor summation
export ICON_TENSOR_PRODUCT_ALT= tensor product alt
export ICON_TENSOR_GRADIENT= tensor gradient
export ICON_TENSOR_DIVERGENCE= tensor divergence
export ICON_TENSOR_CURL= tensor curl
export ICON_TENSOR_LAPLACIAN= tensor laplacian
export ICON_TENSOR_DEL= tensor del
export ICON_TENSOR_DOT_PRODUCT= tensor dot product
export ICON_TENSOR_CROSS_PRODUCT= tensor cross product
export ICON_TENSOR_DIRECT_SUM= tensor direct sum
export ICON_TENSOR_DIRECT_PRODUCT= tensor direct product
export ICON_TENSOR_TENSOR_SUM= tensor tensor sum
export ICON_TENSOR_TENSOR_DIFFERENCE= tensor tensor difference
export ICON_TENSOR_TENSOR_DIVISION= tensor tensor division
export ICON_TENSOR_TENSOR_POWER= tensor tensor power
export ICON_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor square root
export ICON_TENSOR_TENSOR_CUBE_ROOT= tensor tensor cube root
export ICON_TENSOR_TENSOR_NTH_ROOT= tensor tensor nth root
export ICON_TENSOR_TENSOR_INTEGRAL= tensor tensor integral
export ICON_TENSOR_TENSOR_SUMMATION= tensor tensor summation
export ICON_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor product alt
export ICON_TENSOR_TENSOR_GRADIENT= tensor tensor gradient
export ICON_TENSOR_TENSOR_DIVERGENCE= tensor tensor divergence
export ICON_TENSOR_TENSOR_CURL= tensor tensor curl
export ICON_TENSOR_TENSOR_LAPLACIAN= tensor tensor laplacian
export ICON_TENSOR_TENSOR_DEL= tensor tensor del
export ICON_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor dot product
export ICON_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor cross product
export ICON_TENSOR_TENSOR_DIRECT_SUM= tensor tensor direct sum
export ICON_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_LAPLACIAN= tensor tensor tensor laplacian
export ICON_TENSOR_TENSOR_TENSOR_DEL= tensor tensor tensor del
export ICON_TENSOR_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor tensor dot product
export ICON_TENSOR_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor tensor cross product
export ICON_TENSOR_TENSOR_TENSOR_DIRECT_SUM= tensor tensor tensor direct sum
export ICON_TENSOR_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_LAPLACIAN= tensor tensor tensor tensor laplacian
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_DEL= tensor tensor tensor tensor del
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor tensor tensor dot product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor tensor tensor cross product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_SUM= tensor tensor tensor tensor direct sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_LAPLACIAN= tensor tensor tensor tensor tensor laplacian
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DEL= tensor tensor tensor tensor tensor del
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor tensor tensor tensor dot product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor tensor tensor tensor cross product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_SUM= tensor tensor tensor tensor tensor direct sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor tensor tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_LAPLACIAN= tensor tensor tensor tensor tensor laplacian
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DEL= tensor tensor tensor tensor tensor del
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor tensor tensor tensor dot product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor tensor tensor tensor cross product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_SUM= tensor tensor tensor tensor tensor direct sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor tensor tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_LAPLACIAN= tensor tensor tensor tensor tensor laplacian
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DEL= tensor tensor tensor tensor tensor del
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor tensor tensor tensor dot product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor tensor tensor tensor cross product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_SUM= tensor tensor tensor tensor tensor direct sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor tensor tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_LAPLACIAN= tensor tensor tensor tensor tensor laplacian
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DEL= tensor tensor tensor tensor tensor del
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor tensor tensor tensor dot product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor tensor tensor tensor cross product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_SUM= tensor tensor tensor tensor tensor direct sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor tensor tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_LAPLACIAN= tensor tensor tensor tensor tensor laplacian
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DEL= tensor tensor tensor tensor tensor del
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor tensor tensor tensor dot product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor tensor tensor tensor cross product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_SUM= tensor tensor tensor tensor tensor direct sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor tensor tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_LAPLACIAN= tensor tensor tensor tensor tensor laplacian
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DEL= tensor tensor tensor tensor tensor del
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DOT_PRODUCT= tensor tensor tensor tensor tensor dot product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CROSS_PRODUCT= tensor tensor tensor tensor tensor cross product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_SUM= tensor tensor tensor tensor tensor direct sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIRECT_PRODUCT= tensor tensor tensor tensor tensor direct product
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUM= tensor tensor tensor tensor tensor tensor sum
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIFFERENCE= tensor tensor tensor tensor tensor tensor difference
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVISION= tensor tensor tensor tensor tensor tensor division
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_POWER= tensor tensor tensor tensor tensor tensor power
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SQUARE_ROOT= tensor tensor tensor tensor tensor square root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CUBE_ROOT= tensor tensor tensor tensor tensor cube root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_NTH_ROOT= tensor tensor tensor tensor tensor nth root
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_INTEGRAL= tensor tensor tensor tensor tensor integral
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_SUMMATION= tensor tensor tensor tensor tensor summation
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_PRODUCT_ALT= tensor tensor tensor tensor tensor product alt
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_GRADIENT= tensor tensor tensor tensor tensor gradient
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_DIVERGENCE= tensor tensor tensor tensor tensor divergence
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_CURL= tensor tensor tensor tensor tensor curl
export ICON_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_TENSOR_LAPLACian= tensor tensor tensor tensor tensor laplacian