#!/usr/bin/env bash

# Colors taken from tokyonight theme
magenta="0xffbb9af7"
grey="0xff444b6a"
red="0xfff7768e"
blue="0xff7aa2f7"

options=(
  active_color="$red"
  inactive_color="$blue"
  hidpi=on
  style=round
  width=0.0
  blacklist="Screen Studio"
)

borders "${options[@]}"