#!/bin/bash

# Get the absolute path of the script's directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

# Use the script's directory as the base for the storage path
STORAGE_PATH="$SCRIPT_DIR/../../../.aerospace-context"

# Ensure the storage directory exists
if [ ! -d "$STORAGE_PATH" ]; then
  mkdir -p "$STORAGE_PATH"
fi

# Function to get the current workspace name
get_workspace_name() {
  aerospace list-workspaces --focused
}

# Function to set the name for the current workspace
set_workspace_name() {
  local workspace_name="$1"
  local current_workspace=$(get_workspace_name)
  echo "$workspace_name" > "$STORAGE_PATH/$current_workspace"
}

# Function to get the name of the current workspace
get_current_workspace_name() {
  local current_workspace=$(get_workspace_name)
  if [ -f "$STORAGE_PATH/$current_workspace" ]; then
    cat "$STORAGE_PATH/$current_workspace"
  else
    echo "(unnamed)"
  fi
}

# Function to clear the name for the current workspace
clear_workspace_name() {
  local current_workspace=$(get_workspace_name)
  if [ -f "$STORAGE_PATH/$current_workspace" ]; then
    rm "$STORAGE_PATH/$current_workspace"
  fi
}

# Function to list all saved contexts
list_all_contexts() {
  local contexts_list=""
  for file in "$STORAGE_PATH"/*; do
    if [ -f "$file" ]; then
      local workspace_id=$(basename "$file")
      local custom_name=$(cat "$file")
      contexts_list+="$workspace_id $custom_name\n"
    fi
  done

  if [ -n "$contexts_list" ]; then
    local selected_context=$(echo -e "$contexts_list" | fzf --with-nth=2.. --delimiter=' ')
    if [ -n "$selected_context" ]; then
      local selected_workspace_id=$(echo "$selected_context" | awk '{print $1}')
      aerospace workspace "$selected_workspace_id"
    fi
  else
    echo "No contexts saved." >&2
  fi
}

# Main function
main() {
  if [ "$1" = "set" ]; then
    set_workspace_name "$2"
  elif [ "$1" = "get" ]; then
    get_current_workspace_name
  elif [ "$1" = "clear" ]; then
    clear_workspace_name
  elif [ "$1" = "switch" ]; then
    list_all_contexts
  else
    echo "Usage: context [set|get|clear] [name]"
    echo "       context switch"
  fi
}

main "$@"
